"""Gamma zones, cost-aware hedge bands and pin risk.

This module answers the question the user asked for by name -- *how sensitive is
each gamma zone* -- and it answers the trader's objection to answering it with a
prettier chart (requirements s4.4).  A zone is only useful if it is (a) defined by
an objective rule on the book's own gamma profile rather than by eyeballing a
picture, and (b) reported in units you can act on: gamma per 1% **inside** the zone,
distance in percent *and* in sigma-days, a touch probability, the expiries
responsible, and whether you are long or short gamma there.

How a zone is defined (the objective rule)
------------------------------------------
1. Sweep the book's ``gamma_1pct`` over spot with :func:`~fxgamma.portfolio.risk.spot_ladder`
   under the *active sticky convention* -- sticky-strike and sticky-delta give
   materially different profiles and the zone list must say which it used.
2. Keep grid nodes where ``|gamma_1pct| >= threshold * max|gamma_1pct|`` (default
   ``threshold = 0.20``).  This is the "material" test, relative to the book's own
   peak rather than to an absolute number that would need a currency.
3. Cut those nodes into **sign-homogeneous contiguous runs**.  A zone that mixes long
   and short gamma has a meaningless average, and the long/short flag is the first
   thing the trader reads, so the sign is part of the definition, not a label
   applied afterwards.
4. Merge same-sign runs separated by a gap narrower than ``merge_pct`` of spot
   (default 0.25%): a strike cluster split by one thin node is one zone, not two.
5. Cut any surviving run at an interior trough that drops below ``split_trough``
   (default 0.60) of the smaller peak either side of it, so two strike clusters
   joined by a shallow saddle report as two zones rather than one wide one whose
   average describes neither.
6. Drop zones whose share of the book's total gross gamma area is below
   ``min_share`` (default 5%).
7. The zone's centre is the ``|gamma|``-weighted centroid, which lands on the strike
   cluster generating it rather than on the arithmetic middle of the interval.

Because the profile is generated by the strikes, steps 2-5 recover exactly the
"contiguous regions of material gamma clustered around strike concentrations" the
contract asks for, without ever needing to cluster strikes directly -- and it stays
correct for a book whose zones are *between* strikes (a short-gamma hole between two
long strikes has no strike of its own).

Distance units (trader W-7)
---------------------------
``sigma_days`` uses ``sigma_ATM / sqrt(252)``: spot travels on trading days.  The
``sqrt(365)`` basis is for the *economics* (the theta bill, see
``signals.richness.daily_breakeven``) and using it for distance would understate the
achievable daily move by 20% and make far strikes look safer than they are.
Touch probability is a first-passage over calendar time and so uses ``sigma sqrt(T)``
with ``T`` in ACT/365 years, which is the option's own measure.
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from datetime import timezone
from typing import Mapping, Sequence

import numpy as np
import pandas as pd

from ..conventions import PAIRS, expiry_datetime, pair_spec, year_fraction
from ..models import gk
from ..types import Book, GammaZone, HedgeRule, MarketSnapshot
from .risk import STICKY, fx_rate, gamma_pnl_pct, price_book, spot_ladder

__all__ = ["GammaZoneDetail", "gamma_zones", "zone_frame", "hedge_bands", "pin_risk",
           "touch_probability", "sigma_day_pct", "TRADING_DAYS", "CALENDAR_DAYS"]

#: spot travels on trading days -- the basis for distance and probability (W-7)
TRADING_DAYS = 252.0
#: theta is paid on calendar days -- the basis for the breakeven identity (W-7)
CALENDAR_DAYS = 365.0


def sigma_day_pct(sigma: float, basis: float = TRADING_DAYS) -> float:
    """One daily sigma of spot movement, in **percent**.  Distance basis: 252."""
    return 100.0 * float(sigma) / math.sqrt(basis)


def touch_probability(S: float, B: float, T: float, sigma: float,
                      drift: float = 0.0) -> float:
    """P(spot touches level ``B`` at any time before ``T``) under GBM.

    First-passage probability for ``dS/S = drift dt + sigma dW`` (``drift = rd - rf``
    gives the forward measure, which is the right measure for "will I trade in this
    zone before it expires").  With ``x = ln(B/S)`` and ``nu = drift - sigma^2/2``::

        B > S:  N((-x + nu T)/(sigma sqrt T)) + e^{2 nu x / sigma^2} N((-x - nu T)/(sigma sqrt T))
        B < S:  N(( x - nu T)/(sigma sqrt T)) + e^{2 nu x / sigma^2} N(( x + nu T)/(sigma sqrt T))

    Returns 1.0 when the level is already touched, and is capped to [0, 1].

    This is a *touch* probability, not a *finish* probability: it is roughly twice the
    latter for a driftless process, and it is the one that matters for a gamma book
    because you trade the zone when spot gets there, not at the fixing.
    """
    S, B, T, sigma = float(S), float(B), float(T), float(sigma)
    if not (S > 0 and B > 0) or T <= 0.0 or sigma <= 0.0:
        return 1.0 if (S > 0 and B > 0 and abs(math.log(B / S)) < 1e-12) else 0.0
    x = math.log(B / S)
    if abs(x) < 1e-14:
        return 1.0
    nu = float(drift) - 0.5 * sigma * sigma
    sq = sigma * math.sqrt(T)
    N = lambda z: float(gk._norm_cdf(z))            # noqa: E731
    expo = 2.0 * nu * x / (sigma * sigma)
    expo = max(min(expo, 500.0), -500.0)
    if x > 0:
        p = N((-x + nu * T) / sq) + math.exp(expo) * N((-x - nu * T) / sq)
    else:
        p = N((x - nu * T) / sq) + math.exp(expo) * N((x + nu * T) / sq)
    return float(min(max(p, 0.0), 1.0))


# --------------------------------------------------------------------------- #
# the zone type
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class GammaZoneDetail(GammaZone):
    """``types.GammaZone`` plus the numbers that make it actionable.

    Subclassing keeps the frozen contract type intact: a ``list[GammaZoneDetail]``
    *is* a ``list[GammaZone]``, so any consumer written against the contract keeps
    working and the extra fields are additive (no contract change requested).

    Fields added here
    -----------------
    side                 ``"long"`` / ``"short"`` gamma inside the zone
    lo_pct, hi_pct       zone edges as % from spot (signed)
    edge_pct             distance to the **near edge**, signed % (0 if spot is inside)
    distance_sigma_days  distance to the centre in daily sigmas (sqrt 252 basis)
    edge_sigma_days      distance to the near edge in daily sigmas
    sigma_atm            the ATM vol used for the sigma-day and probability maths
    horizon_days         calendar days to the zone's **nearest** expiry
    touch_prob           P(touch the near edge before ``horizon_days``)
    pnl_to_center        P&L (quote ccy) if spot goes to the zone centre, fully
                         repriced under the active sticky convention -- not a
                         quadratic approximation
    gamma_pnl_to_center  the ``0.005*G1*S*x^2`` approximation, for comparison
    delta_at_center      the delta (base ccy) the book would carry inside the zone
    delta_at_near_edge   the delta at the edge you would reach first
    peak_spot            spot level of the largest |gamma| in the zone
    strikes              the strikes generating the zone
    notional_base        gross option notional attributable to the zone
    contribution         each contributing position's gamma_1pct at the centre
    ccy / fx_to_report / *_rep  the CG-1 reporting-ccy copies
    """
    side: str = "long"
    lo_pct: float = 0.0
    hi_pct: float = 0.0
    edge_pct: float = 0.0
    distance_sigma_days: float = 0.0
    edge_sigma_days: float = 0.0
    sigma_atm: float = float("nan")
    horizon_days: float = float("nan")
    touch_prob: float = float("nan")
    pnl_to_center: float = 0.0
    gamma_pnl_to_center: float = 0.0
    delta_at_center: float = 0.0
    delta_at_near_edge: float = 0.0
    peak_spot: float = 0.0
    spot: float = 0.0
    strikes: tuple[float, ...] = ()
    notional_base: float = 0.0
    n_positions: int = 0
    sticky: str = "strike"
    ccy: str = ""
    base_ccy: str = ""
    fx_to_report: float = 1.0
    fx_base_to_report: float = 1.0
    report_ccy: str = "USD"
    gamma_1pct_rep: float = 0.0
    peak_gamma_1pct_rep: float = 0.0
    pnl_to_center_rep: float = 0.0
    delta_at_center_rep: float = 0.0
    contribution: tuple[tuple[str, float], ...] = ()


def _runs(mask: np.ndarray, sign: np.ndarray) -> list[tuple[int, int]]:
    """Contiguous index runs where ``mask`` holds and ``sign`` is constant."""
    out: list[tuple[int, int]] = []
    i = 0
    n = mask.size
    while i < n:
        if not mask[i]:
            i += 1
            continue
        j = i
        while j + 1 < n and mask[j + 1] and sign[j + 1] == sign[i]:
            j += 1
        out.append((i, j))
        i = j + 1
    return out


def _split_troughs(a: int, b: int, mag: np.ndarray, frac: float) -> list[tuple[int, int]]:
    """Split a run at any interior trough deep enough to be two strike clusters.

    A run is cut at its deepest interior minimum when that minimum falls below
    ``frac`` of the smaller of the two peaks either side of it (a prominence test).
    Without this, two separately-hedgeable strike concentrations joined by a shallow
    saddle report as one very wide zone whose "average gamma inside" describes
    neither of them.  Recurses so a three-cluster run yields three zones.
    """
    if b - a < 4 or not (0.0 < frac < 1.0):
        return [(a, b)]
    # candidates are *interior local minima* only.  The run's own endpoints sit at the
    # materiality threshold, so the plain minimum over the interior is always next to
    # an edge and would split nothing useful.
    loc = [j for j in range(a + 1, b)
           if mag[j] <= mag[j - 1] and mag[j] <= mag[j + 1]]
    if not loc:
        return [(a, b)]
    scores = [float(mag[j]) / max(min(float(mag[a: j + 1].max()),
                                      float(mag[j: b + 1].max())), 1e-30) for j in loc]
    k = int(np.argmin(scores))
    if scores[k] >= frac:
        return [(a, b)]
    j = loc[k]
    return _split_troughs(a, j, mag, frac) + _split_troughs(j, b, mag, frac)


def gamma_zones(book: Book, mkt: MarketSnapshot, pair: str, *,
                lo_pct: float = -8.0, hi_pct: float = 8.0, n: int = 321,
                sticky: str = "strike", threshold: float = 0.20,
                min_share: float = 0.05, merge_pct: float = 0.25,
                split_trough: float = 0.60,
                horizon_days: float | None = None, report_ccy: str = "USD",
                marks: Mapping[str, float] | None = None,
                max_zones: int = 8) -> list[GammaZoneDetail]:
    """Contiguous spot regions where the book's gamma is materially concentrated.

    Returns :class:`GammaZoneDetail` (a ``types.GammaZone`` subclass), sorted by
    ``|distance_pct|`` so the zone you are standing in comes first.  See the module
    docstring for the definition and for why the sigma-day basis is 252.

    Parameters
    ----------
    threshold : node kept when ``|G1| >= threshold * max|G1|`` on the swept grid.
    min_share : zones below this share of total gross gamma area are dropped.
    merge_pct : same-sign runs closer than this (% of spot) are one zone.
    split_trough : a run is cut at an interior trough that falls below this fraction
        of the smaller adjacent peak, so two strike clusters joined by a shallow
        saddle report as two zones.  Set to 0 to disable splitting.
    horizon_days : horizon for the touch probability.  Default: calendar days to the
        zone's own nearest contributing expiry, which is the honest horizon -- a zone
        that dies on Friday should not be scored on a one-month touch probability.
    """
    if sticky not in STICKY:
        raise ValueError(f"sticky must be one of {STICKY}, got {sticky!r}")
    sub = book.filter(pair)
    if not sub.options:
        return []
    spec = pair_spec(pair)
    S0 = float(mkt.spot[pair])
    lad = spot_ladder(sub, mkt, pair, lo_pct=lo_pct, hi_pct=hi_pct, n=n,
                      sticky=sticky, report_ccy=report_ccy, marks=marks)
    S = lad["spot"].to_numpy(float)
    g = lad["gamma_1pct"].to_numpy(float)
    pv = lad["pv"].to_numpy(float)
    dl = lad["delta_base"].to_numpy(float)
    if not np.isfinite(g).any() or np.nanmax(np.abs(g)) <= 0.0:
        return []

    dS = np.gradient(S)
    area_total = float(np.sum(np.abs(g) * dS))
    peak = float(np.nanmax(np.abs(g)))
    mask = np.abs(g) >= threshold * peak
    sign = np.sign(g)
    runs = _runs(mask, sign)

    # merge same-sign runs separated by a thin gap
    merged: list[tuple[int, int]] = []
    for r in runs:
        if merged:
            a, b = merged[-1]
            if sign[r[0]] == sign[a] and (S[r[0]] - S[b]) / S0 * 100.0 <= merge_pct:
                merged[-1] = (a, r[1])
                continue
        merged.append(r)

    # 4b. split runs that contain two distinct strike clusters (see _split_troughs)
    mag = np.abs(g)
    split: list[tuple[int, int]] = []
    for a, b in merged:
        split.extend(_split_troughs(a, b, mag, float(split_trough)))
    merged = split

    rows = price_book(sub, mkt, report_ccy=report_ccy, marks=marks)
    rows = rows[(rows["kind"] == "option") & (~rows["expired"].astype(bool))]
    fq = fx_rate(spec.quote, report_ccy, mkt)
    fb = fx_rate(spec.base, report_ccy, mkt)
    rd, rf = mkt.rd_rf(pair, PAIRS)
    pv_at = lambda x: float(np.interp(x, S, pv))          # noqa: E731
    dl_at = lambda x: float(np.interp(x, S, dl))          # noqa: E731
    pv0 = pv_at(S0)

    zones: list[GammaZoneDetail] = []
    for a, b in merged:
        sl = slice(a, b + 1)
        w = np.abs(g[sl])
        area = float(np.sum(w * dS[sl]))
        share = area / area_total if area_total > 0 else 0.0
        if share < min_share:
            continue
        lo, hi = float(S[a]), float(S[b])
        center = float(np.sum(S[sl] * w) / np.sum(w)) if np.sum(w) > 0 else 0.5 * (lo + hi)
        pk = int(a + int(np.argmax(np.abs(g[sl]))))
        side = "long" if g[pk] > 0 else "short"

        # which positions make this zone: their gamma at the zone centre
        contrib: list[tuple[str, float]] = []
        for _, r in rows.iterrows():
            T = float(r["T"])
            if T <= 0:
                continue
            sig = float(r["vol"])
            if sticky == "delta":
                sig = float(mkt.surfaces[pair].vol(float(r["strike"]) * S0 / center, T))
            gg = gk.gk_greeks(center, float(r["strike"]), T, rd, rf, sig, int(r["cp"]),
                              float(r["notional_base"]), int(r["direction"]),
                              delta_convention=spec.delta_convention)
            contrib.append((str(r["id"]), gg.gamma_1pct))
        tot = sum(abs(c) for _, c in contrib) or 1.0
        main = [c for c in contrib if abs(c[1]) >= 0.10 * tot] or contrib
        ids = {i for i, _ in main}
        picked = rows[rows["id"].isin(ids)]
        expiries = tuple(sorted({d for d in picked["expiry"]})) if len(picked) else ()
        strikes = tuple(sorted({float(k) for k in picked["strike"]})) if len(picked) else ()
        notional = float(picked["notional_base"].sum()) if len(picked) else 0.0

        # horizon and vol for distance / probability
        if expiries:
            # each leg's own cut: a TKY15 and an NY10 leg on the same date are hours apart
            near_T = min(year_fraction(mkt.asof, r["expiry"], str(r["cut"]) or "NY10")
                         for _, r in picked.iterrows())
        else:
            near_T = float(rows["T"].min()) if len(rows) else 0.0
        hz = float(horizon_days) / 365.0 if horizon_days is not None else near_T
        sig_atm = float(mkt.surfaces[pair].atm(max(near_T, 1e-6))) if pair in mkt.surfaces else float("nan")
        sd = sigma_day_pct(sig_atm)                       # one daily sigma, in %

        inside = lo <= S0 <= hi
        near_edge = S0 if inside else (lo if S0 < lo else hi)
        dist_pct = (center - S0) / S0 * 100.0
        edge_pct = 0.0 if inside else (near_edge - S0) / S0 * 100.0
        tp = 1.0 if inside else touch_probability(S0, near_edge, hz, sig_atm, rd - rf)

        pnl_c = pv_at(center) - pv0
        approx = gamma_pnl_pct(float(np.mean(g[sl])), S0, dist_pct)
        z = GammaZoneDetail(
            pair=pair, lo=lo, hi=hi, center=center,
            gamma_1pct=float(np.mean(g[sl])),
            peak_gamma_1pct=float(g[pk]),
            share_of_total=share,
            expiries=expiries,
            label=("long gamma pocket" if side == "long"
                   else "short gamma pocket / pin risk"),
            distance_pct=dist_pct,
            side=side,
            lo_pct=(lo - S0) / S0 * 100.0, hi_pct=(hi - S0) / S0 * 100.0,
            edge_pct=edge_pct,
            distance_sigma_days=dist_pct / sd if sd else float("nan"),
            edge_sigma_days=edge_pct / sd if sd else float("nan"),
            sigma_atm=sig_atm, horizon_days=hz * 365.0, touch_prob=tp,
            pnl_to_center=pnl_c, gamma_pnl_to_center=approx,
            delta_at_center=dl_at(center), delta_at_near_edge=dl_at(near_edge),
            peak_spot=float(S[pk]), spot=S0, strikes=strikes,
            notional_base=notional, n_positions=int(len(picked)), sticky=sticky,
            ccy=spec.quote, base_ccy=spec.base,
            fx_to_report=fq, fx_base_to_report=fb, report_ccy=report_ccy.upper(),
            gamma_1pct_rep=float(np.mean(g[sl])) * fb,
            peak_gamma_1pct_rep=float(g[pk]) * fb,
            pnl_to_center_rep=pnl_c * fq,
            delta_at_center_rep=dl_at(center) * fb,
            contribution=tuple(sorted(main, key=lambda c: -abs(c[1]))),
        )
        zones.append(z)

    zones.sort(key=lambda z: (abs(z.distance_pct), -z.share_of_total))
    return zones[:max_zones]


def zone_frame(zones: Sequence[GammaZone]) -> pd.DataFrame:
    """Zones as a table for the Risk page (REQ-042)."""
    cols = ["pair", "label", "side", "lo", "center", "hi", "peak_spot",
            "gamma_1pct", "peak_gamma_1pct", "gamma_1pct_rep", "share_of_total",
            "distance_pct", "distance_sigma_days", "edge_pct", "edge_sigma_days",
            "touch_prob", "horizon_days", "pnl_to_center_rep", "delta_at_center",
            "delta_at_near_edge", "notional_base", "strikes", "expiries",
            "sigma_atm", "sticky", "ccy", "report_ccy"]
    if not zones:
        return pd.DataFrame({c: pd.Series(dtype="object") for c in cols})
    recs = []
    for z in zones:
        recs.append({c: getattr(z, c, None) for c in cols})
    return pd.DataFrame(recs)[cols]


# --------------------------------------------------------------------------- #
# hedge bands (CG-3)
# --------------------------------------------------------------------------- #
#: per-pair round-trip spot cost in bp of traded notional.  W-13: a single global
#: 0.2bp is right for EURUSD in interbank size, ~2x too tight for AUD/NZD/CAD and
#: 10-25x too tight for the Scandies.  These are the defaults `HedgeRule.cost_bp`
#: should have; passing an explicit `rule.cost_bp` still wins.
COST_BP = {
    "EURUSD": 0.2, "USDJPY": 0.3, "GBPUSD": 0.4, "USDCHF": 0.5, "USDCAD": 0.5,
    "AUDUSD": 0.5, "NZDUSD": 0.8, "USDSEK": 3.0, "USDNOK": 3.0,
    "EURJPY": 0.6, "EURGBP": 0.6, "EURCHF": 0.6,
}
#: trader Q-2: band = 15% of the pair's gross option notional, floored at a clip
DEFAULT_BAND_PCT = 15.0
DEFAULT_CLIP = 1_000_000.0


def _band_width(sub: Book, mkt: MarketSnapshot, pair: str, rule: HedgeRule | None,
                gamma_budget: float | None, gamma: float) -> tuple[float, str, str]:
    """(half-width in base ccy, source, warning)."""
    gross = sum(abs(o.notional_base) for o in sub.options)
    warn = ""
    if gamma_budget is not None:
        return float(abs(gamma_budget)), "gamma_budget", warn
    if rule is None:
        return max(DEFAULT_BAND_PCT / 100.0 * gross, DEFAULT_CLIP), "default 15% of gross notional", warn
    if rule.band_delta and rule.band_delta > 0:
        return float(rule.band_delta), "rule.band_delta", warn
    if rule.mode == "gamma_budget":
        return max(abs(rule.target_delta) or DEFAULT_CLIP, DEFAULT_CLIP), "rule.gamma_budget", warn
    # Amendment v1.6 CR-1: band_pct is a FRACTION of gross option notional
    # (0.25 = 25%), not "0.25 percent". Reading it as a percent made the frozen
    # default ~60x too tight -- a 10mm book rehedging on a 25k delta drift.
    bp = float(rule.band_pct)
    if bp > 1.0:
        warn = (f"rule.band_pct={bp} is a fraction of gross notional, so this asks for "
                f"{bp * 100:.0f}% of notional. If you meant {bp:.0f}%, pass {bp / 100:g}.")
    return (max(bp * gross, 0.0),
            f"rule.band_pct={bp:g} ({bp * 100:g}% of gross notional)", warn)


def hedge_bands(book: Book, mkt: MarketSnapshot, pair: str, *,
                gamma_budget: float | None = None, rule: HedgeRule | None = None,
                report_ccy: str = "USD", risk_aversion: float = 1e-6,
                sigma: float | None = None, span_pct: float = 8.0,
                marks: Mapping[str, float] | None = None) -> pd.DataFrame:
    """Rebalance bands and the next trigger, cost-aware (REQ-043, CG-3).

    Two rows (``side`` = ``"lower"`` / ``"upper"``) with the spot level at which the
    band is breached, the distance in pips and %, the size that would be traded and
    what it costs.  Band sources, in precedence order: ``gamma_budget`` ->
    ``rule.band_delta`` -> ``rule.band_pct`` (% of the pair's gross option notional)
    -> the desk default of 15% floored at a 1mm clip (trader Q-2).

    Cost awareness
    --------------
    Two independent numbers, both reported, neither hidden in ``app/``:

    * **Turnover economics of the chosen band.**  For a band of half-width ``h`` in
      spot, boundary hits arrive at ``sigma_daily^2 S^2 / h^2`` per day; each costs
      ``H * S * lambda`` (``lambda`` = one-way proportional cost).  ``exp_hedges_day``,
      ``exp_cost_day_rep`` and the gamma income the band captures
      (``exp_gamma_pnl_day_rep``) let the trader see whether the band pays for itself.
    * **The cost-optimal width** ``band_ww_base``: the Whalley-Wilmott (1997)
      asymptotic band under proportional costs and exponential utility,
      ``H = (1.5 * lambda * e^{-rd T} * S * Gamma^2 / gamma_risk)^{1/3}``.  It is an
      *indication*, not the default -- it needs a risk-aversion parameter
      (``risk_aversion``, in 1/quote-ccy) that no market quotes.

    Costs default to the per-pair :data:`COST_BP` table rather than one global
    number (trader W-13); ``rule.cost_bp`` overrides it when supplied.
    """
    sub = book.filter(pair)
    spec = pair_spec(pair)
    S0 = float(mkt.spot[pair])
    rd, rf = mkt.rd_rf(pair, PAIRS)
    df = price_book(sub, mkt, report_ccy=report_ccy, marks=marks)
    live = df[~df["expired"].astype(bool)] if len(df) else df
    delta = float(live["delta_base"].sum()) if len(live) else 0.0
    gamma = float(live["gamma"].sum()) if len(live) else 0.0
    g1 = float(live["gamma_1pct"].sum()) if len(live) else 0.0
    target = float(rule.target_delta) if rule is not None else 0.0

    H, src, warn = _band_width(sub, mkt, pair, rule, gamma_budget, gamma)
    cost_bp = float(rule.cost_bp) if rule is not None and rule.cost_bp else COST_BP.get(pair, 0.5)
    lam = cost_bp / 2.0 / 1e4                      # one-way, fraction of traded value
    fq = fx_rate(spec.quote, report_ccy, mkt)

    if sigma is None:
        Ts = [float(t) for t in live["T"]] if len(live) else []
        Tref = min([t for t in Ts if t > 0], default=1.0 / 12.0)
        sigma = float(mkt.surfaces[pair].atm(Tref)) if pair in mkt.surfaces else 0.08
    sig_day = float(sigma) / math.sqrt(TRADING_DAYS)

    # trigger levels: where the ladder's delta first crosses target +/- H
    lad = spot_ladder(sub, mkt, pair, lo_pct=-span_pct, hi_pct=span_pct, n=401,
                      sticky="strike", report_ccy=report_ccy, marks=marks)
    Sg, dg = lad["spot"].to_numpy(float), lad["delta_base"].to_numpy(float)

    def _cross(level: float, direction: int) -> float:
        idx = np.where(Sg > S0)[0] if direction > 0 else np.where(Sg < S0)[0][::-1]
        prev_S, prev_d = S0, float(np.interp(S0, Sg, dg))
        for i in idx:
            cur_S, cur_d = float(Sg[i]), float(dg[i])
            if (prev_d - level) * (cur_d - level) <= 0 and cur_d != prev_d:
                return prev_S + (level - prev_d) * (cur_S - prev_S) / (cur_d - prev_d)
            prev_S, prev_d = cur_S, cur_d
        return float("nan")

    # Whalley-Wilmott indicative width.
    # The constant is POLICY dependent and this was wrong: 3/2 is the hedge-to-EDGE
    # constant, but everything in this repo hedges to TARGET, whose constant is 6 --
    # a band 4**(1/3) = 1.587x wider. Taken from bandopt.POLICY_CONST rather than
    # restated here, because a duplicated formula is exactly how band_pct and
    # COMPONENTS drifted before. See docs/09_hedging_theory.md.
    ww = float("nan")
    if gamma != 0.0 and risk_aversion > 0:
        from .bandopt import POLICY_CONST
        Tref = min([float(t) for t in live["T"] if float(t) > 0], default=1.0 / 12.0)
        ww = (POLICY_CONST["center"] * lam * math.exp(-rd * Tref)
              * S0 * gamma ** 2 / risk_aversion) ** (1.0 / 3.0)

    out = []
    for side, sgn in (("lower", -1), ("upper", +1)):
        level = target + sgn * H
        trig = _cross(level, sgn)
        h_spot = abs(trig - S0) if np.isfinite(trig) else float("nan")
        trade = -(level - target)                       # trade back to target
        cost = abs(trade) * (trig if np.isfinite(trig) else S0) * lam
        hits = (sig_day * S0) ** 2 / h_spot ** 2 if h_spot and np.isfinite(h_spot) else float("nan")
        found = bool(np.isfinite(trig))
        out.append({
            "pair": pair, "side": side, "spot": S0,
            "trigger_found": found,
            "trigger_note": ("" if found else
                             f"delta never reaches {level:,.0f} within +/-{span_pct:g}% "
                             "of spot -- this side of the band cannot be breached by a "
                             "move of that size (short-gamma wing or an offsetting leg)"),
            "delta_base": delta, "target_delta": target,
            "band_base": H, "band_source": src, "warning": warn,
            "band_level_delta": level,
            "trigger_spot": trig,
            "dist_pips": (trig - S0) / spec.pip if np.isfinite(trig) else float("nan"),
            "dist_pct": (trig - S0) / S0 * 100.0 if np.isfinite(trig) else float("nan"),
            "dist_sigma_days": ((trig - S0) / S0 * 100.0) / sigma_day_pct(sigma)
                               if np.isfinite(trig) else float("nan"),
            "trade_base_at_trigger": trade,
            "est_cost": cost, "est_cost_rep": cost * fq,
            "cost_bp_round_trip": cost_bp,
            "exp_hedges_day": hits,
            "exp_cost_day_rep": hits * abs(H) * S0 * lam * fq if np.isfinite(hits) else float("nan"),
            "exp_gamma_pnl_day_rep": (0.5 * gamma * h_spot ** 2 * hits * fq
                                      if np.isfinite(hits) else float("nan")),
            "gamma_1pct": g1, "gamma": gamma, "sigma_atm": float(sigma),
            "band_ww_base": ww, "risk_aversion": risk_aversion,
            "in_band": abs(delta - target) <= H,
            "report_ccy": report_ccy.upper(), "ccy": spec.quote,
        })
    return pd.DataFrame(out)


# --------------------------------------------------------------------------- #
# pin risk (REQ-045, corrected per trader W-1)
# --------------------------------------------------------------------------- #
def pin_risk(book: Book, mkt: MarketSnapshot, pair: str, *,
             horizon_days: float = 3.0, ks: Sequence[int] = (10, 25, 50),
             include_all: bool = False, report_ccy: str = "USD",
             marks: Mapping[str, float] | None = None) -> pd.DataFrame:
    """Per-strike expiry risk: what you inherit, and the discontinuity at the cut.

    The spec's formula, and why it is wrong
    ---------------------------------------
    REQ-045 labels ``sum(direction * cp * notional_base)`` "the delta discontinuity
    inherited at expiry".  That expression is the delta you inherit **if the option
    finishes in the money**, which is a different number, and read as a discontinuity
    it is sign-wrong on every put.

    Derivation of the right one.  At the cut the hedge ratio collapses to the exercise
    indicator, so a position's inherited base-ccy delta is::

        D(S) = direction * N * cp * 1{cp (S - K) > 0}

    Evaluate either side of the strike:

    ==================  ===============  ===============  ==================
    position            D just below K   D just above K   jump = above-below
    ==================  ===============  ===============  ==================
    long call  (+1,+1)        0               +N                +N
    long put   (+1,-1)       -N                0                +N
    short call (-1,+1)        0               -N                -N
    short put  (-1,-1)       +N                0                -N
    ==================  ===============  ===============  ==================

    so ``jump_at_strike = sum(direction * N)`` -- **independent of cp**.  A long call
    gains +N crossing up; a long put loses its -N, which is also +N.  The ``cp`` in
    the spec's formula is exactly what flips the sign on puts.

    (Premium-adjusted pairs carry an extra ``K/S`` on the inherited delta, which is
    identically 1 at the crossing point ``S = K``, so the jump is unchanged.  The
    ``delta_if_*`` columns below do carry it, evaluated at ``S = K``.)

    Columns
    -------
    ``delta_if_above`` / ``delta_if_below``
        the base-ccy spot position you wake up with if spot finishes above / below
        this strike -- two labelled numbers, never one called "the discontinuity"
        (trader W-1, Q-9).
    ``jump_at_strike``
        the discontinuity itself, ``sum(direction * N)``.
    ``p_above``, ``p_within_<k>p``
        finish probabilities under the forward measure at the strike's own smile vol.
    ``dist_sigma_days``
        distance in daily sigmas on the **sqrt(252)** basis (W-7); rows inside
        ``0.5`` sigma-days are flagged ``pin_alert``.
    ``gamma_1pct``
        the book's gamma at that strike right now -- what it costs you to be wrong.
    """
    sub = book.filter(pair)
    spec = pair_spec(pair)
    S0 = float(mkt.spot[pair])
    rd, rf = mkt.rd_rf(pair, PAIRS)
    df = price_book(sub, mkt, report_ccy=report_ccy, marks=marks)
    df = df[df["kind"] == "option"] if len(df) else df
    if not len(df):
        return pd.DataFrame(columns=["pair", "strike", "expiry", "cut", "jump_at_strike"])
    if not include_all:
        df = df[df["days_to_expiry"].astype(float) <= float(horizon_days)]
    if not len(df):
        return pd.DataFrame(columns=["pair", "strike", "expiry", "cut", "jump_at_strike"])

    now = mkt.asof if mkt.asof.tzinfo else mkt.asof.replace(tzinfo=timezone.utc)
    rows = []
    for (K, expiry, cut), grp in df.groupby(["strike", "expiry", "cut"], sort=True):
        K = float(K)
        T = float(grp["T"].max())
        sig = float(grp["vol"].mean()) if np.isfinite(grp["vol"]).any() else float("nan")
        if not np.isfinite(sig) or sig <= 0:
            sig = float(mkt.surfaces[pair].vol(K, max(T, 1e-6))) if pair in mkt.surfaces else 0.1
        sgn = grp["direction"].astype(float) * grp["notional_base"].astype(float)
        cp = grp["cp"].astype(float)
        pa = spec.delta_convention.endswith("_pa")
        fac = 1.0                                  # K/S evaluated at S = K
        d_above = float((sgn * np.where(cp > 0, 1.0, 0.0)).sum()) * fac
        d_below = float((sgn * np.where(cp < 0, -1.0, 0.0)).sum()) * fac
        jump = float(sgn.sum())
        assert abs((d_above - d_below) - jump) < 1e-6 * max(1.0, abs(jump))

        cut_dt = expiry_datetime(expiry, str(cut))
        # finish probabilities in the forward measure at this strike's smile vol
        def p_above_level(level: float) -> float:
            if T <= 0 or sig <= 0 or level <= 0:
                return 1.0 if S0 > level else 0.0
            _, d2, _ = gk.d1_d2(S0, level, T, rd, rf, sig)
            return float(gk._norm_cdf(float(d2)))

        sd = sigma_day_pct(sig)
        row = {
            "pair": pair, "strike": K, "expiry": expiry, "cut": str(cut),
            "cut_utc": cut_dt, "hours_to_cut": (cut_dt - now).total_seconds() / 3600.0,
            "T": T, "days_to_expiry": T * 365.0,
            "spot": S0, "vol": sig,
            "dist_pips": (K - S0) / spec.pip, "dist_pct": (K - S0) / S0 * 100.0,
            "dist_sigma_days": ((K - S0) / S0 * 100.0) / sd if sd else float("nan"),
            "notional_base": float(grp["notional_base"].sum()),
            "signed_notional": float(sgn.sum()),
            "n_legs": int(len(grp)),
            "gamma_1pct": float(grp["gamma_1pct"].sum()),
            "gamma_1pct_rep": float(grp["gamma_1pct_rep"].sum()),
            "delta_if_above": d_above, "delta_if_below": d_below,
            "jump_at_strike": jump,
            "spec_formula_itm_delta": float((sgn * cp).sum()),
            "p_above": p_above_level(K),
            "premium_adjusted": pa,
            "report_ccy": report_ccy.upper(),
        }
        for k in ks:
            lo_, hi_ = K - k * spec.pip, K + k * spec.pip
            row[f"p_within_{k}p"] = max(p_above_level(lo_) - p_above_level(hi_), 0.0)
        row["pin_alert"] = bool(abs(row["dist_sigma_days"]) <= 0.5) if np.isfinite(
            row["dist_sigma_days"]) else False
        rows.append(row)
    out = pd.DataFrame(rows).sort_values(["expiry", "strike"], ignore_index=True)
    return out
